title: Discord4J
description: Discord4J Project Site
author: Discord4J
logo: /static/img/avatar.png
github: https://github.com/Discord4J
about: A REST/WS wrapper for the official Discord Bot API.

baseurl: ""
url: "https://discord4j.com"

allowsearch: true

# disqus_shortname: aboutashu
google_analytics: UA-100029628-1

# share:
#   twitter_username: \#
#   fb_appid: 000000000000


enableTags: true
tagarray: ["discord", "java", "discord4j", "d4j", "wrapper"]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
